vim.api.nvim_set_hl(0, 'CursorColumn', { bg='#303030' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg='#303030' })
vim.opt.autoindent = true
vim.opt.cursorcolumn = true
vim.opt.cursorline = true
vim.opt.expandtab = false
vim.opt.hlsearch = false
vim.opt.ignorecase = true
vim.opt.incsearch = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.showmatch = true
vim.opt.smartcase = true
vim.opt.tabstop = 4
vim.opt.undofile = true
vim.opt.wrap = false
