. ~/.bash.d/just.sh
. ~/.bash.d/asciidoc.sh
. ~/.bash.d/flashbiter.sh
. ~/.bash.d/aqualove.sh
. ~/.bash.d/bash-darwin.sh
. ~/.bash.d/bash.sh
. ~/.bash.d/kind.sh
. ~/.bash.d/cabal.sh
. ~/.bash.d/chef.sh
. ~/.bash.d/common.sh
. ~/.bash.d/cygwin.sh
. ~/.bash.d/docker.sh
. ~/.bash.d/eksctl.sh
. ~/.bash.d/emacs.sh
. ~/.bash.d/enscript.sh
#. ~/.bash.d/rancher_desktop.sh
. ~/.bash.d/fzf.sh
. ~/.bash.d/git.sh
. ~/.bash.d/gnu.sh
. ~/.bash.d/golang.sh
. ~/.bash.d/google-cloud-sdk.sh
. ~/.bash.d/kubectl.sh
. ~/.bash.d/krew.sh
. ~/.bash.d/kpt.sh
. ~/.bash.d/helm.sh
. ~/.bash.d/less.sh
. ~/.bash.d/mutt.sh
. ~/.bash.d/ncurses.sh
. ~/.bash.d/nginx.sh
. ~/.bash.d/nvm.sh
. ~/.bash.d/node.sh
. ~/.bash.d/openssl.sh
. ~/.bash.d/poetry.sh
. ~/.bash.d/python3.sh
. ~/.bash.d/ruby.sh
. ~/.bash.d/rust.sh
. ~/.bash.d/rvm.sh
. ~/.bash.d/selenium.sh
. ~/.bash.d/serverless.sh
. ~/.bash.d/shfmt.sh
. ~/.bash.d/sphinx-doc.sh
. ~/.bash.d/sqlite3.sh
. ~/.bash.d/terraform.sh
. ~/.bash.d/deno.sh
. ~/.bash.d/travis.sh
. ~/.bash.d/acorn.sh
. ~/.bash.d/vault.sh
. ~/.bash.d/ytt.sh
. ~/.bash.d/skaffold.sh
. ~/.bash.d/pack.sh
. ~/.bash.d/direnv.sh
. ~/.bash.d/pyenv.sh
. ~/.bash.d/z.sh
. ~/.bash.d/edgedb.sh
. ~/.bash.d/mysql-client.sh

### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="/Users/mtm/.rd/bin:$PATH"
