#!/usr/bin/env zsh


autoload -Uz compinit
compinit
bindkey \^U backward-kill-line


. ~/.shell/brew

. ~/.shell/asciidoc
. ~/.shell/cabal
. ~/.shell/deno
. ~/.shell/docker
. ~/.shell/edgedb
. ~/.shell/emacs
. ~/.shell/envman
. ~/.shell/functions
. ~/.shell/gnu
. ~/.shell/golang
. ~/.shell/google-cloud-sdk
. ~/.shell/less
. ~/.shell/mysql-client
. ~/.shell/openssl
. ~/.shell/pnpm
. ~/.shell/poetry
. ~/.shell/aqualove
. ~/.shell/pyenv
. ~/.shell/ruby
. ~/.shell/rvm
. ~/.shell/skaffold
. ~/.shell/sphinx-doc
. ~/.shell/sqlite3
. ~/.shell/z
. ~/.zsh.d/acorn
. ~/.zsh.d/atuin
. ~/.zsh.d/direnv
. ~/.zsh.d/eksctl
. ~/.zsh.d/fzf
. ~/.zsh.d/git
. ~/.zsh.d/just
. ~/.zsh.d/kubectl
. ~/.zsh.d/zinit
. ~/.shell/nix
. ~/.zsh.d/oh-my-zsh
