#!/usr/bin/env zsh

. ~/.zsh.d/keybindings
. ~/.zsh.d/acorn
. ~/.zsh.d/direnv
. ~/.zsh.d/eksctl
. ~/.zsh.d/git
. ~/.zsh.d/just
. ~/.zsh.d/kubectl
. ~/.zsh.d/oh-my-zsh
. ~/.zsh.d/atuin
. ~/.zsh.d/zoxide
. ~/.shell/rc
