(require 'user-init-helm)

(setq-default TeX-master t)
(setq-default auto-mode-case-fold t)
(setq-default column-number-mode t)
(setq-default default-fill-column 72)
(setq-default delete-by-moving-to-trash t)
(setq-default display-buffer-reuse-frames t)
(setq-default enable-recursive-minibuffers t)
(setq-default encoding 'utf-8)
(setq-default global-font-lock-mode t)
(setq-default inhibit-startup-message t)
(setq-default initial-scratch-message "")
(setq-default large-file-warning-threshold 50000000)
(setq-default lexical-binding t)
(setq-default menu-bar-mode nil)
(setq-default require-final-newline t)
(setq-default ring-bell-function 'ignore)
(setq-default scroll-bar-mode nil)
(setq-default scroll-preserve-screen-position 1)
(setq-default sentence-end-double-space nil)
(setq-default split-height-threshold nil)
(setq-default split-width-threshold 0)
(setq-default truncate-lines t)
(setq-default visible-bell t)
(setq-default indent-tabs-mode nil)

(put 'upcase-region 'disabled nil)

(defalias 'yes-or-no-p 'y-or-n-p)

(provide 'user-init)
