#!/usr/bin/env bash

# Source ~/.atuin/bin/env only if atuin is not already in PATH
! command -v atuin &>/dev/null && [[ -f "$HOME/.atuin/bin/env" ]] && . "$HOME/.atuin/bin/env"

! command -v atuin &>/dev/null && return

# shellcheck source=/dev/null
[[ -f "$HOME/.bash-preexec.sh" ]] && source "$HOME/.bash-preexec.sh"

eval "$(atuin init bash --disable-up-arrow --disable-ctrl-r)"

eval "$(atuin gen-completions --shell=bash)"

# Return early if not interactive shell
[[ $- != *i* ]] && return

bind -x '"\C-]": "__atuin_history"'