#!/usr/bin/env zsh
[ ! -x "$(command -v fd)" ] && return
[ ! -x "$(command -v fzf)" ] && return

cd_to_dir() {
   local selected_dir
   selected_dir=$(fd -t d . "$1" | fzf +m --height 50% --preview 'tree -C {}')
   if [[ -n "$selected_dir" ]]; then
       cd "$selected_dir" || return 1
   fi
}

alias cdd='cd_to_dir ~/Desktop/'
alias cds='cd_to_dir'
