#!/usr/bin/env zsh

! command -v fzf &>/dev/null && return

[[ ! -o interactive ]] && return

fzfopen() {
    "$@" | fzf --tac --bind 'enter:execute:nvim {} </dev/tty'
}

fzf-obsidian() {
    fzf --preview 'cat {}' | xargs -I {} bash -c 'open "obsidian://open?path=$(printf "%s" "{}" | jq -sRr @uri)"'
}
