#!/usr/bin/env zsh

! command -v git &>/dev/null && return
export GIT_PAGER=cat
parse_git_branch() {
 ref=$(git symbolic-ref HEAD 2>/dev/null) || return
 echo "("${ref#refs/heads/}")"
}
setopt PROMPT_SUBST
PS1='[%n@%m:%1~$(parse_git_branch)]$ '
