#!/usr/bin/env zsh

if [[ $OSTYPE == 'darwin'* ]]; then
    export NVM_DIR="$HOME/.nvm"
    [ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"
    [ -s "$NVM_DIR/current" ] && export PATH="$NVM_DIR/versions/node/$(cat $NVM_DIR/current)/bin:$PATH"
else
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/current" ] && export PATH="$NVM_DIR/versions/node/$(cat $NVM_DIR/current)/bin:$PATH"
fi
