#!/usr/bin/env zsh

[ ! -x $HOME/.local/bin/zoxide ] && return

export PATH="$HOME/.local/bin:$PATH"

! command -v zoxide &>/dev/null && return

eval "$(zoxide init zsh)"
ZOXIDE_COMPLETIONS_FILE="${XDG_CACHE_HOME:-$HOME/.cache}/zoxide/completions.zsh"
[[ -f $ZOXIDE_COMPLETIONS_FILE ]] && [[ ! $(find "$ZOXIDE_COMPLETIONS_FILE" -mtime +7) ]] || {
  mkdir -p "${ZOXIDE_COMPLETIONS_FILE%/*}"
  zoxide init --cmd z zsh --no-aliases > "$ZOXIDE_COMPLETIONS_FILE"
}

z() {
 if [ "$1" = "-t" ]; then
   zoxide query -l -s "${@:2}"
 else
   __zoxide_z "$@"
 fi
}

source "$ZOXIDE_COMPLETIONS_FILE"
