#!/usr/bin/env zsh

[[ -s /usr/local/etc/profile.d/z.sh ]] && . /usr/local/etc/profile.d/z.sh

[ ! -x $HOME/.local/bin/zoxide ] && return

export PATH="$HOME/.local/bin:$PATH"

! command -v zoxide &>/dev/null && return

eval "$(zoxide init zsh --cmd=z)"
ZOXIDE_COMPLETIONS_FILE="${XDG_CACHE_HOME:-$HOME/.cache}/zoxide/completions.zsh"
[[ -f $ZOXIDE_COMPLETIONS_FILE ]] && [[ ! $(find "$ZOXIDE_COMPLETIONS_FILE" -mtime +7) ]] || {
  mkdir -p "${ZOXIDE_COMPLETIONS_FILE%/*}"
  zoxide init --cmd z zsh --no-aliases > "$ZOXIDE_COMPLETIONS_FILE"
}

source "$ZOXIDE_COMPLETIONS_FILE"

