bugzilla:
	bzr co -v bzr://bzr.mozilla.org/bugzilla/trunk bugzilla
bztools:
	git clone git://github.com/LegNeato/bztools.git
git: 
	git clone git://git.kernel.org/pub/scm/git/git.git
pybugz:
	git://github.com/williamh/pybugz.git
update:
	(cd bugzilla && bzr update)
	(cd bztools && git pull)
	(cd git && git pull)
	(cd pybugz && git pull)
