(source melpa)
(source melpa-stable)
(source gnu)

(depends-on "pallet")
(depends-on "req-package")
(depends-on "helm")
(depends-on "editorconfig")
(depends-on "request")
(depends-on "terraform-mode")
(depends-on "yasnippet")

